{% set name = "django-sql-explorer" %}
{% set version = "5.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b5fbe5bdf8e86768e252f8ef69a0fb336e8255b5bef504aaefff83440871080e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - sphinx
    - pip
  run:
    - python >=3.8
    - django >=3.2
    - sqlparse >=0.4.0
    - requests >=2.2
    - django-cryptography-django5 ==2.2
    - cryptography >=42.0

test:
  imports:
    - explorer
  #commands:
    #- pip check
  requires:
    - pip

about:
  home: https://github.com/chrisclark/django-sql-explorer
  summary: A pluggable app that allows users (admins) to execute SQL, view, and export the results.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
